name: naiapp
description: "NAI App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.9+6

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # HTTP & Network
  http: ^1.2.2
  
  # UI Components
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  auto_size_text: ^3.0.0
  photo_view: ^0.15.0
  reorderables: ^0.6.0
  flutter_screenutil: ^5.9.3
  lottie: ^3.1.2
  
  # Storage & Data
  shared_preferences: ^2.3.1
  dartz: ^0.10.1
  
  # Images & Media
  image_gallery_saver_plus: ^4.0.1
  image: ^4.5.4
  image_picker: ^1.1.2
  cross_file: ^0.3.4+2
  exif: ^3.3.0
  gal: ^2.3.1
  
  # System & Device
  flutter_foreground_task: ^9.1.0
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.3.0
  path_provider: ^2.1.5
  
  # Utils
  cupertino_icons: ^1.0.8
  mime: ^1.0.5
  intl: ^0.20.2
  package_info_plus: ^9.0.0


dev_dependencies:
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  freezed: ^3.0.3

  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/lotties/
    - assets/images/
    - assets/images/logos/
    - assets/icons/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Black.ttf
        - asset: assets/fonts/Pretendard/Pretendard-Bold.ttf
        - asset: assets/fonts/Pretendard/Pretendard-Light.ttf
        - asset: assets/fonts/Pretendard/Pretendard-Medium.ttf
        - asset: assets/fonts/Pretendard/Pretendard-Regular.ttf
        - asset: assets/fonts/Pretendard/Pretendard-Thin.ttf

